### PR TITLE
This does not compile. TapToPlace contains several errors

### PR DESCRIPTION
**Pull request by LocalJoost**
"private virtual void" for several methods is not valid -> "protected virtual void". And the IInputClickHandler.OnInputClicked is implemented as protected, but should be public, or the class does not implement the interface.

### CODE REVIEW

**Comment by HodgsonSDAS** [comment]
My apologies.  Thanks for the hotfix @LocalJoost

**Comment by LocalJoost** [comment]
You are welcome :)

**Comment by HodgsonSDAS** [comment]
@NeerajW This one is critical.

**Comment by NeerajW** [comment]
Yeah just tried this. Thanks @LocalJoost !

**Comment by LocalJoost** [comment]
You are welcome @NeerajW

**Pull request merged**
