### PR TITLE
Document how to get started

### LINKED ISSUE #89: `-unsafe` compiler option required
To use HoloToolkit it is necessary to set the `-unsafe` compiler option. I'm new to C# so I'm not sure what this means, but I did find the following text on the Unity forums:

"Again, using unsafe doesn't give you much advantages, it just opens up for a huge variety of errors, mistakes and unexpected behaviour. Unless you know exactly what you do and you use pointers sparsely you shouldn't go for an unsafe context. " (http://answers.unity3d.com/questions/804103/how-to-enable-unsafe-and-use-pointers.html)

Is it wise to require unsafe? If this needs to remain then this should be documented in the readme (see link above for documentation)

### PR DESCRIPTION
**Pull request by rgardler**
As a newbie to C# and Unity (and obviously HoloLens) I took some wrong turns that led me down the path of importing HoloToolkit as a Git submodule rather than as a Unity package. As a result I raised a couple of invalid issues here (#89 and #90). 

This Getting Started guide is intended to prevent others making the same mistakes (and for me to have your team review my approach to ensure I got it right this time).

Fixes #89 and #90

### CODE REVIEW

**Comment by jwittner** [comment]
This would also resolve #94. I think we should update the portion on dealing with the unsafe code to suggest copying the *.rsp files contained in the HoloToolkit-Unity/Assets directory instead of asking users to create their own.

**Comment by NeerajW** [comment]
If user's use it as a package either creating one themselves or from the Unity asset store, then do we still need to specify the *rsp dependency?

**Comment by jwittner** [comment]
It looks like it'll work fine as long as the package includes the *rsp files. If we have directions on creating their own package we should note that things outside of Assets/HoloToolkit are required.

**Comment by NeerajW** [comment]
Agreed. Ross please add that information in here as well.

**Comment by rgardler** [comment]
I already made the change relating to *.rsp files after a colleague tested on a new project. See the most recent commit - https://github.com/Microsoft/HoloToolkit-Unity/pull/91/commits/e580d7afe5866d0f45b5b5ebe2623a4a1412a96b

**Comment by rgardler** [comment]
Oh... wait, I should have checked that commit before saying I'd already done it. Looks like I forgot to save the file after the last edit. Will update momentarily.

**Comment by jwittner** [comment]
The steps outlined do look to include everything in the toolkit, so I'm good here.

**Pull request merged**
