### PR TITLE
Split the documentation out into sub documents

### LINKED ISSUE #82: Documentation is hard to navigate and collaborate on.
Right now we've got documentation spread throughout the README and the Wiki. This causes a few problems:

- The front page of our GitHub is polluted with in-depth scripting documentation.
- The wiki documentation is hard to collaborate on.
- Documentation is hard to navigate and doesn't connect well.

After investigating using pages ( see comment below ) I'm recommending we simply reorganize the wiki to look something like this:

- Manual
 - Logical descriptions of systems, like the sections of the wiki we have now
 - Descriptions of prefabs and the exposed editor data, should include screenshots from the editor
 - Tutorials
 - Should contain links to relevant Scripting API sections.
- Scripting API
 - API descriptions of script types and their API
 - All the descriptions that currently live in the README
 - Should contain links to relevant Manual sections.

It'd be nice to auto-generate the Scripting API section someday, which should be possible given some VS XML documentation to Markdown Open Source projects out there.

### PR DESCRIPTION
**Pull request by jwittner**
Also made all internal links relative so they work from any branch.

Fixes #82

### CODE REVIEW

**Comment by NeerajW** [comment]
@jwittner is it typical to call the README.md files by folder specific names in open source projects? I have usually seen them being called README.md in each folder. Just curios if that makes it more discoverable and easier to give instructions on?

**Comment by jwittner** [comment]
@NeerajW I'm not certain what others do on this front. I thought burying things would make them harder to find - maybe we can put all but the README into a Docs/ folder? It would reduce top level clutter, but keep the documentation pretty discoverable.

**Comment by NeerajW** [comment]
I don't think the common practice is to create a separate docs folder. I like the fact that each folder has its own readme. That is certainly better than what it is now.

I am just wondering if it should be called README.md consistently in all folders.

**Comment by robertlevy** [comment]
Yes - by using readme.md as the name, GitHub will render it by default when somebody navigates to a folder.

**Comment by NeerajW** [comment]
@robertlevy thank you for weighing in. 
@jwittner want to make that change? I also prefer that and per my research seems like a standard practice.

**Comment by jwittner** [comment]
No problem, I can move things into the Unity feature folders and rename to README.md. =)

**Comment by jwittner** [comment]
Let me know if anything else needs changing. =)

**Comment by jwittner** [comment]
@NeerajW Would love to get this in before any new documentation changes get through. =)

**Comment by NeerajW** [comment]
Josh thanks for making the updates. Merging.

**Pull request merged**
