### PR TITLE
FpsDisplay fixes

### PR DESCRIPTION
**Pull request by HodgsonSDAS**
Removed redundant text mesh.
Updated prefab's pivot to be pre-selected to Y axis. (was unset previously)

### CODE REVIEW

**Comment by keveleigh** [comment]
Interesting, it looks like we lost X as a pivot axis in https://github.com/Microsoft/HoloToolkit-Unity/commit/37247d9489910735b833f5bb20b3be840a07a5b0#diff-40903bdeebaf71c08a776607e5cb91e0

Was that intentional @maxouellet ?

**Comment by maxouellet** [comment]
@keveleigh if I remember correctly, it was removed by an internal Microsoft team because it didn't work, or at least didn't have the behavior that one would expect (or didn't serve much purpose as implemented).

I'm completely OK with adding it back if we get it to work properly and if it is useful.

**Comment by HodgsonSDAS** [comment]
It wasn't required for it to work properly.

**Comment by keveleigh** [comment]
@maxouellet Sounds good! I'll create an Issue and take a look at it.

@HodgsonSDAS It might not be required for the FPS prefab to work, but Billboard is a normally used component as well.

**Pull request merged**
