### PR TITLE
Spatial Mapping Updates

### PR DESCRIPTION
**Pull request by angelaHillier**
This update addresses issues #144, #143, and #39. Unfortunately, most code looks new, even though it's simply being moved to a new location. Here's a list of what the major changes are in this PR:
1) Adds the ObjectSurfaceObserver for loading meshes from a room file to the SpatialMapping prefab (replaces the old FileSurfaceObserver).
2) Moves the FileSurfaceObserver onto the RemoteMapping prefab, for saving/loading files from a remote mapping session.
3) Moves all scripts related to RemoteMapping into a separate folder called 'RemoteMapping'.
4) Moves all scripts related to Processing into a separate folder called 'SpatialProcessing'.
5) Removes RemoteMapping prefab from the SpatialProcessing.unity test scene. SpatialProcessing test will now load a .obj file when running in Unity via the ObjectSurfaceObserver script.
6) Adds a RemoteMapping.unity test scene to help test the RemoteMapping scripts.
7) Updates spatial mapping documentation.
8) Removes Plugins\WSA\x64\PlaneFinding.dll (which was failing WACK for some people and is not actually used by anything).

### CODE REVIEW

**Comment by jwittner** [comment]
Whoa! A monster change. =)

Can you outline a few test cases I can use to verify all the surface area of this change?

**Comment by angelaHillier** [comment]
It looks like a monster, but it's more a reshuffle. Instead of deprecating RemoteMapping, we chose to move all relevant scripts to a different folder. Most developers should *never* need to use these scripts, so when importing HoloToolkit, you can quickly de-select this folder to exclude them. 

The SpatialMapping prefab now matches what we use in Holograms 230 (includes the ObjectSurfaceObserver instead of the FileSurfaceObserver). And the RemoteMapping prefab now includes the FileSurfaceObserver to save/load files from the remote session. If someone prefers the old behavior (using FileSurfaceObserver), they can edit that script to load a file automatically, but we would prefer developers to use ObjectSurfaceObserver instead.

To test, run the following scenes:
1) SpatialMapping\Tests\SpatialProcessing.unity
    a) Run this in Editor, to verify that ObjectSurfaceObserver is working (it should load meshes from the SRMesh.obj file in the 'support' folder) and that the removal of the WSA x64 PlaneFinding.dll did not break ability to do plane finding.
    b) Run this on HoloLens or emulator to verify that the live surface observer still works fine, along with plane finding.

2)SpatialMapping\Tests\RemoteMapping.unity
a) Updated instructions for running this scene are in documentation, but here's the flow:
Open port 11000 on your PC's firewall. Set the IPv4 address of your PC on the RemoteTarget and RemoteSource components of the RemoteMapping object. Build and deploy to HoloLens. Once running on HoloLens, press the 'play' button to start running the app in the Unity Editor. Press the 'N' key to accept meshes from the network. On HoloLens, say "Send Meshes" to send meshes to Unity. Watch the meshes appear in Unity. Press the 'S' key to save the meshes to your PC. Stop running in Unity by pressing 'Play'. Restart in Unity by pressing 'Play' again and then press the 'L' key to load the meshes from the saved file (which will use the old FileSurfaceObserver). Note: This change also makes the 'S' 'L' 'N' keycodes and 'Send Meshes' command configurable in the Editor.

Those two scenes should be enough to cover the new ObjectSurfaceObserver code (which is already used in Holograms 230), and changes made to SpatialMappingManager, RemoteMapping prefab, and SpatialMapping prefab.

Note: I also ran the TapToPlace and PlaneFinding test scenes to verify that functionality was not regressed there.
Thanks!
~Angela

**Comment by NeerajW** [comment]
Changes look good to me.
@jwittner please merge when you are ready.

**Comment by jwittner** [comment]
Thanks @angelaHillier! I ran the first SpatialProcessing tests above and everything worked great, I'll trust you on the RemoteMapping tests. =)

**Pull request merged**
