### PR TITLE
Mic Stream Demo Fixes

### PR DESCRIPTION
**Pull request by StephenHodgson**
- Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/574
- Reverted `Start` back to `Awake`.
- Updated Instructions.

### CODE REVIEW

**Comment by keveleigh** [comment]
Will this reopen #555? Or has that been fixed another way?

**Comment by StephenHodgson** [comment]
That was fixed another way.

**Comment by StephenHodgson** [comment]
Confirmed that it was fixed a different way.

**Comment by keveleigh** [comment]
I don't see a folder that corresponds to the added meta file.
image

**Comment by StephenHodgson** [comment]
Removed

**Pull request merged**
