### PR TITLE
Add HoloShell like shader for rendering spatial mesh on air tap #335

### PR DESCRIPTION
**Pull request by pinkwerks**
Needs a component to drive the radius and center location. Not sure of the best way to do this the "HoloToolkit Way".

### CODE REVIEW

**Comment by HodgsonSDAS** [comment]
@pinkwerks not sure what you mean by needed component.

**Comment by pinkwerks** [comment]
The shader doesn't drive itself. Something has to supply a changing radius and tap location to the shader. I'm not sure how to use the HoloToolkit so I figured someone who knows how it works could supply this data to the material.

**Comment by HodgsonSDAS** [comment]
Probably best if this component goes on the cursor prefab.  I'll work with you on getting something together.

**Comment by HodgsonSDAS** [comment]
Sorry it's been a few days, but the move to Unity 5.5 has kept my attention from this.

**Comment by HodgsonSDAS** [comment]
Hey @pinkwerks I've pulled your request and found you're not using the latest master. 

Could you pull the latest so I can work with getting this shader setup with the defaultCursor.prefab?

Thanks

**Comment by HodgsonSDAS** [comment]
Here's a branch of my fork you can pull from.  I tried to submit a PR on your for @pinkwerks, but I think you may have your permissions setup to not accept any. 

I just wanted to share what I've been working on with you. This branch also includes the spatial mapping folder refactor and organizational changes.

https://github.com/HodgsonSDAS/HoloToolkit-Unity/tree/HTK-SpatialMappingTap

**Comment by HodgsonSDAS** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/issues/335

**Comment by HodgsonSDAS** [comment]
@pinkwerks could you address the conflicts please?

**Pull request merged**
