### PR TITLE
Renamed Example and Test Scenes to be more descriptive.

### PR DESCRIPTION
**Pull request by HodgsonSDAS**
fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/270

### CODE REVIEW

**Comment by HodgsonSDAS** [comment]
Not sure how there's a conflict without file changes, but okay. haha.

**Comment by HodgsonSDAS** [comment]
@jwittner  or @NeerajW could you guys tell me what the conflict is exactly so I can fix?  Thanks.

**Comment by NeerajW** [comment]
Perhaps delete the old Main.unity and its meta file?
Also ensure you have the latest Sync in your fork.

**Comment by HodgsonSDAS** [comment]
Yup. Nothing to compare.
image

**Comment by HodgsonSDAS** [comment]
good call.

**Pull request merged**
