### PR TITLE
Updating Test Scene

### PR DESCRIPTION
**Pull request by cre8ivepark**
Fixed 'missing prefabs' issue on the TextPrefabSamplesTest.unity scene.

### CODE REVIEW

**Comment by NeerajW** [comment]
What about this meta file that you checked in earlier?
https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/UI/Scripts.meta

**Comment by cre8ivepark** [comment]
@NeerajW Even though the Script folder is empty, Unity generate that meta file. Not sure if it is okay to remove it?

**Comment by keveleigh** [comment]
@cre8ivepark Yep, it's probably best to delete that folder unless you plan on using it, and the meta file can be safely deleted as well. Git won't track empty folders.

**Comment by cre8ivepark** [comment]
@keveleigh Thanks! I have deleted empty Script folder and Script.meta file.

**Comment by jwittner** [comment]
Nit: It would be nice if the project set the Asset Serialization Mode to Force Text so that Assets/HoloToolkit-Examples/Text/TextPrefabSamplesTest.unity was a text file and not binary.

**Comment by HodgsonSDAS** [comment]
@jwittner I have just the solution.

```
namespace Saab.Editor;

[InitializeOnLoad]
public class EnforceEditorSettings
{
    static EnforceEditorSettings()
    {
        #region Editor Settings

        if (EditorSettings.serializationMode != SerializationMode.ForceText)
        {
            EditorSettings.serializationMode = SerializationMode.ForceText;
            UnityEngine.Debug.Log("Setting Force Text Serialization");
        }

        if (!EditorSettings.externalVersionControl.Equals("Visible Meta Files"))
        {
            EditorSettings.externalVersionControl = "Visible Meta Files";
            UnityEngine.Debug.Log("Updated external version control mode: " + EditorSettings.externalVersionControl);
        }

        #endregion
    }
```

**Pull request merged**
