### PR TITLE
Focus object fix

### PR DESCRIPTION
**Pull request by killerantz**
When looking at adding events for gesture recognition start and end so that my UI elements could display a visual down and up state, I noticed that when focused changed, the new focused object was being set before the gestures were canceled. Canceling gestures sends the recognition end event, but to the new focused object.

While I was updating the logic, adding the "SendMessageOptions.DontRequireReceiver" to the OnSelect message seemed to match the intent that any object may or may not be listening for the OnSelect message.

### CODE REVIEW

**Comment by jwittner** [comment]
Looks like a good fix! I'll give it a day or so for others to comment then we'll move it in.

**Comment by HodgsonSDAS** [comment]
Is this related to https://github.com/Microsoft/HoloToolkit-Unity/pull/209

**Comment by HodgsonSDAS** [comment]
> Would using delegates require the focused object to register with GestureManager on gaze and then unregister on gaze off?

No, not in my implementation of it. I actually decided to open an issue https://github.com/Microsoft/HoloToolkit-Unity/issues/224 just on this. I'd like your input there. 

I'm actually quite intrigued by the vast difference between the HoloToolkit we used while working at Microsoft and the version that's here on GitHub.

**Comment by killerantz** [comment]
@HodgsonSDAS please pass along a sample of how you are using delegates; do you have a branch or snippets to share?

My assumption is a typical usage, like exposing the tap event in GestureManager. an interactable object would register to that event OnAwake or OnEnable. When the GestureManager calls the delegate, the interactive object checks if they are in focus, comparing themselves to GestureManager.FocusedObject. Or is there something more?

I can update my branch and see how this works in my test project. From what you are saying, it sounds like a best practice, but I'm no authority by any means.

**Comment by HodgsonSDAS** [comment]
See https://github.com/Microsoft/HoloToolkit-Unity/pull/225

**Pull request merged**
