### PR TITLE
Fix for file updates on open.

### PR DESCRIPTION
**Pull request by jwittner**
Example.unity is converted to text from binary because project is
configured for Force Text assets.

Missing meta files are added for SpatialSound/Scripts/UAudioManager
hierarchy.

### CODE REVIEW

**Comment by jwittner** [comment]
The goal is that cloning and then opening the project should not result in changes. These are the changes that do result.

**Comment by alexdrenea** [comment]
I'm glad you brought this up. I was actually curious as to why there are meta files in the project.
Isn't it the case that when you use the Toolkit, you import it in your project and Unity generates the meta files at that point?

**Comment by jwittner** [comment]
The meta files contain information about the related asset files, including the GUID used to reference them. This is true for every asset type, including scripts, prefabs, models, textures, etc. For assets with import options, the options are stored in the meta files as well.

If we don't include the meta files, then basically all of the internal references of the project will break.

**Comment by jwittner** [comment]
On a side note - I've been experimenting with using the Toolkit as a git submodule to my project and symlinking to the HoloToolkit folder under the Assets folder from my projects Assets folder. It works really well and makes updating the Toolkit and contributing to it while developing real use cases remarkably easy.

The only gotcha is that Windows is sensitive about creating symlinks and you either have to be an admin or the user needs local group policy permission.

**Comment by NeerajW** [comment]
@jwittner could you please explain more the steps around symlinks?

**Comment by jwittner** [comment]
No problem!

I created a template for Unity HoloLens Application Template onto my github here: https://github.com/jwittner/HoloToolkit-Unity-AppTemplate

You should be able to check that out for how the structure works.

Regarding cloning and symlinks on Windows 10. To create symlinks on Windows you either have to be an Administrator in an elevated prompt or you have to have the Local Group Policy for symlinks enabled for your account: http://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7.

**Pull request merged**
