### PR TITLE
fixed Unity error caused by missing MonoBehaviour

### PR DESCRIPTION
**Pull request by DominicBoettger**
The missing MonoBehaviour caused an error in Unity.

### CODE REVIEW

**Comment by HodgsonSDAS** [comment]
@DominicBoettger I did see that this script is attached to the sharing prefab by default.  I'll look into this a bit more and see what the guys at MSFT were tying to do with these changes.

**Comment by HodgsonSDAS** [comment]
The real problem was the MSFT internal HTK got merged into the Github HTK without much checking.

https://github.com/Microsoft/HoloToolkit-Unity/blame/f3e121ad1c61fba1569ecca876324ba86a86b09d/Assets/HoloToolkit/Sharing/Scripts/SessionUsersTracker.cs.meta

**Comment by DominicBoettger** [comment]
Hi @HodgsonSDAS 

Exactly, i was confused by the errors i got in Unity from the Sharing.prefab from the prefabs folder. I will take a look at the prefab from the test scene.

Thanks a lot!

**Comment by HodgsonSDAS** [comment]
@DominicBoettger do you mind if we close this in favor of opening a new issue?

**Comment by DominicBoettger** [comment]
That's okay. Thanks for your work!

**Pull request closed without merging**
