### PR TITLE
Added unit tests for VectorExtensions

### PR DESCRIPTION
**Pull request by aalmada**
It's hard for the reviewers to test all functionalities so I think it's a good idea to start enforcing a unit tests requirement.
Here is an example for the VectorExtensions. While working on it, I noticed that the latest functionalities added are actually not extensions. One good reason for them to exist...
I placed the unit tests in a HoloToolkit-UnitTests folder under Assets to keep the HoloToolkit deployment simple.
Unit tests execution is integrated into the Unity editor (since 5.3). It doesn't require the Unity Test Tools from the asset store.
To run all the tests: 
1. Click on the menu item Window | Editor Tests Runner. 
2. Click on the button Run All.

### CODE REVIEW

**Comment by HodgsonSDAS** [comment]
This is awesome. We should definitely consider using this more often.

**Comment by NeerajW** [comment]
@aalmada great idea! Love it!
Could you please add a README to that folder on how to run them?

**Comment by HodgsonSDAS** [comment]
https://docs.unity3d.com/Manual/testing-editortestsrunner.html

**Comment by aalmada** [comment]
Sorry but I've been away. I'll add the README.md soon.

**Comment by HodgsonSDAS** [comment]
No worries @aalmada

**Comment by aalmada** [comment]
I added the requested README.md. Feedback is welcome.

**Comment by HodgsonSDAS** [comment]
I like it.

Requiring to run a test before making a PR is hard to enforce haha.
Although anyone reviewing could make a pull and test themselves before accepting the merge.

**Pull request merged**
