### PR TITLE
Updated Font Shader to correctly handle uGUI stencil operations and color changes through text components

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/526 and adds the ability to change color through the text component properly.

Now we don't need a new material for every color font.

If font looks strange simply find `3DtextShader`, right click, and reimport.

### CODE REVIEW

**Comment by HodgsonSDAS** [comment]
I should probably include that stencil fix in this PR as well... Hmm...

**Comment by S-Hodgson-MMOARgames** [comment]
I'm actually going to close this and fix the real issue. The shader needs to know about the Text components color value. We shouldn't have to make a new material every time we want the font to be a different color.

**Comment by NeerajW** [comment]
Reached out to them :)

**Comment by cre8ivepark** [comment]
Hi @StephenHodgson Thanks for this update!
I tried to apply updated shader code but it gives me this error. Could you please take a look? Is this because my GPU is old? Mine is somewhat old one (AMD FirePro M4000 on 2013 laptop)
2017-02-24 09_15_30-unity 5 5 0f3 personal 64bit - textprefabsamplestest unity - textprefabtest2 -
2017-02-24 09_15_43-textprefabtest2 - microsoft visual studio

**Comment by StephenHodgson** [comment]
Did you try reimporting the shader?

I'll do some research into the root cause of the problem.
That is a pretty common property.

**Comment by cre8ivepark** [comment]
@StephenHodgson 
Somehow VS editor was adding a space between - and 1 when I pasted the code.
If I update Offset - 1, -1 to Offset -1, -1 the error is fixed. 
I will try new shader, Thanks!

**Comment by StephenHodgson** [comment]
Try removing the space between the "-" and 1

**Comment by StephenHodgson** [comment]
Haha we noticed it at the same time. Too funny.

I don't believe we need to specify a fallback shader, but I could add one if needed.

**Comment by cre8ivepark** [comment]
@StephenHodgson Tested it and works well! This will really save a lot of effort and time for creating materials for different colors. Thank you for the great update!

**Pull request merged**
