### PR TITLE
Fix some GazeRuler issues

### LINKED ISSUE #152: Rename "ploygon" to "polygon"
Typo in [IPloygonClosable ](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/GazeRuler/Scripts/IPloygonClosable.cs)interface.

### LINKED ISSUE #155: GazeRuler: Another unused variable warning
Assets/HoloToolkit-Examples/GazeRuler/Scripts/Test/LineTest.cs(21,13): warning CS0168: The variable `cameraDir' is declared but never used

### PR DESCRIPTION
**Pull request by ChangweiZhang**
I have rename some error class name and delete some unused variables

Fixes #155 
Fixes #152

### CODE REVIEW

**Comment by NeerajW** [comment]
@ChangweiZhang looks like your fork is out of sync with Microsoft/master.
Please update your fork from Microsoft/master and then merge and update the pull request.

**Comment by jwittner** [comment]
Fixes #155

**Comment by ChangweiZhang** [comment]
Hi, I have added some missing meta files and update my fork from Microsoft/master. Thank you

**Comment by jwittner** [comment]
Everything seemed to be working for me in the emulator.

**Pull request merged**
