### PR TITLE
Force Text Asset Serialization and visible meta files

### PR DESCRIPTION
**Pull request by HodgsonSDAS**
@jwittner I don't know why this isn't the default settings in Unity.

### CODE REVIEW

**Comment by andrewgotow** [comment]
The addition of this file caused my serialization mode to switch, and broke every serialized reference in the project. Please add a confirmation dialogue before changing project configurations without warning.

**Comment by StephenHodgson** [comment]
@andrewgotow, sorry about that. This was an attempt to control the way people were contributing to the repository.  We were also having issues with broken references because of the mixed serialization, which is why I had originally suggested this change. I apologize for any inconveniences.

**Comment by andrewgotow** [comment]
No problem, and thank you for the explanation! Would it be possible for me to submit a PR which adds a confirmation dialogue before altering the settings?

**Comment by StephenHodgson** [comment]
Yes, please do that.

**Comment by andrewgotow** [comment]
The log statements did immediately point me in the right direction, and I appreciate that!

I think my situation was just an isolated incident. I've changed serialization mode mid-project a number of times, and it generally doesn't cause an issue.

The confirmation dialogues wouldn't prevent it from breaking references, but it would allow users to delay the switch until they're ready, hopefully giving teams with bizarre project structures a little time to deal with things first.

I've modified the `EnforceEditorSettings.cs` script to present a confirmation dialogue when first opening a project, or importing the HoloToolkit, however I can't decide if it is too annoying... Either way, feel free to have a look.

https://github.com/andrewgotow/HoloToolkit-Unity/pull/1

**Pull request merged**
