### PR TITLE
Added SpeechInputHandler

### PR DESCRIPTION
**Pull request by aalmada**
SpeechInputHandler is to be used with the SpeechInputSource. It allows the mapping of keywords to script methods using the Unity editor inspector.
This PR also includes a custom editor for the SpeechInputHandler that shows the registered keywords on the SpeechInputSources as a dropdown. This way, the user doesn't have to type the keywords again and prevents typing errors.

collapsed
expanded
dropdown

### CODE REVIEW

**Comment by aalmada** [comment]
@maxouellet This version uses a UnityEvent to reference the method to be called. I don't like because it forces the user to specify what game object the script is on. What do you think?

**Comment by maxouellet** [comment]
@aalmada I don't like it, but it's the beginner-friendly way to do it in Unity, so I don't have a problem with it as long as usage of this SpeecInputHandler is optional. I think it's a good way to make things accessible to beginners, without forcing more advanced programmers into a pattern that breaks encapsulation and good coding practices

**Comment by HodgsonSDAS** [comment]
I'm just worried about all the different places we can assign keywords.

Ideally this should be centralized on the keyword manager.

**Comment by aalmada** [comment]
@HodgsonSDAS In your own words, "SpeechInputHandler only give devs the ability to assign events to keywords created on SpeechInputSource". 
The SpeechInputSource/SpeechInputHandler pair can reproduce the KeywordManager behavior but I agree that it's in bit more complex form. I would also agree that the KeywordManager is enough for most applications. I just believe that there should also exist InputManager-based speech handling for more complex applications and that's implemented by SpeechInputSource. The use of the SpeechInputHandler is optional and targets users that like visual development.
IMHO KeywordManager, SpeechInputSource and SpeechInputHandler can co-exist as long as their use cases are well documented.
@maxouellet I also hate the use o UnityEvent but, to my best knowledge, it's the only out-of-the-box solution. The implementation of an alternative will take some time. It requires the implementation of custom serialization and more custom editors. 
What about the SpeechInputHandler itself and the keywords dropdown?

**Comment by aalmada** [comment]
The dropdown now doesn't show the keywords already assigned in this handler:
expanded2

Unfortunately, duplicates are still possible. For example, when a new line is added. A warning is shown now:
duplicate

**Comment by HodgsonSDAS** [comment]
I don't think that it's bad for the keyword to be assigned more than once, but bad it could assigned in multiple locations inside the editor. Sorry if that sounds confusing.

**Comment by aalmada** [comment]
@HodgsonSDAS It's expected to exist multiple handlers in the scene hierarchy and these can have the same keywords assigned. This is because of the bubbling-like InputManager message routing.
The SpeechInputHandler maps the keywords to the UnityEvent using a dictionary so it doesn't support keyword duplicates. UnityEvent allows the assignment of multiple methods to the same keyword (notice the plus and minus signs in the tab).

**Comment by HodgsonSDAS** [comment]
Ahh okay, then I suppose that is fine then. I didn't realize that is the intended behavior.

**Comment by HodgsonSDAS** [comment]
@aalmada You've got some conflicts.

**Comment by HodgsonSDAS** [comment]
@aalmada You've got some conflicts.

**Pull request merged**
