### PR TITLE
Moved all test folders into HoloToolkit-Tests

### PR DESCRIPTION
**Pull request by StephenHodgson**
Resolves https://github.com/Microsoft/HoloToolkit-Unity/issues/589

### CODE REVIEW

**Comment by HoloFan** [comment]
Sounds like a good idea to me. It will clean up the repository quite a bit.

**Comment by StephenHodgson** [comment]
@HoloFan, just waiting for other people to review the pull request. You can help that along by submitting your review.

**Comment by thebanjomatic** [comment]
@StephenHodgson Any suggestions on how I can test / review this change? Should I just sync it down and do a search for all scene files and make sure they still open?

**Comment by StephenHodgson** [comment]
Just make sure no test folders exist in HoloToolkit folders.
Make a new test project you'd like to try it in.
Make a new asset package containing only the HoloToolkit folder.
New asset package should import without errors.

**Comment by thebanjomatic** [comment]
Thanks I'll give that a go tonight when I get home.

**Pull request merged**
